server:
    port: 8000
grpc:
    host: "127.0.0.1"
    port: 8081
spring:
    application:
        name: grpc-client
    zipkin:
        base-url: http://localhost:9411
        service:
            name: grpc-client
    sleuth:
        enabled: true
        baggage:
            remote-fields:
                - X-USER-ID
            local-fields:
                - X-USER-ID
            correlation-fields:
                - X-USER-ID
#        feign:
#            processor:
#                enabled: true
#        http:
#            enabled: true
#        web:
#            enabled: true
#        grpc:
#            enabled: true
feign:
    client:
        config:
            catalogApi:
                url: localhost:8080

logging:
    level:
        org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
