server:
    port: 8000

grpc:
    client:
        grpc-server:
            negotiation-type: plaintext
            enable-keep-alive: true
            keep-alive-without-calls: true
            address: 'static://127.0.0.1:8081'

spring:
    application:
        name: grpc-client
    sleuth:
        enabled: true
        baggage:
            remote-fields:
                - X-USER-ID
            local-fields:
                - X-USER-ID
            correlation-fields:
                - X-USER-ID
                -
feign:
    client:
        config:
            catalogApi:
                url: localhost:8080

logging:
    level:
        org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
