server:
    port: 8080
grpc:
    port: 8081

spring:
    application:
        name: grpc-server
    sleuth:
        enabled: true
        baggage:
            remote-fields:
                - USER-ID
            local-fields:
                - USER-ID
            correlation-fields:
                - USER-ID
    h2:
        console:
            enabled: true
            path: /h2-console
    jpa:
        show-sql: false
        generate-ddl: true
        hibernate:
            ddl-auto: none
    datasource:
        driverClassName: org.h2.Driver
        url: jdbc:h2:~/test
        username: sa
        password:

logging:
    level:
        org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG