server:
    port: 8080
grpc:
    port: 8081

spring:
    application:
        name: grpc-server
    zipkin:
        base-url: http://localhost:9411
        service:
            name: grpc-server
    sleuth:
        sampler:
            probability: 1.0
        enabled: true
        baggage:
            remote-fields:
                - X-USER-ID
            local-fields:
                - X-USER-ID
            correlation-fields:
                - X-USER-ID
        grpc:
              enabled: true
    h2:
        console:
            enabled: true
            path: /h2-console
    jpa:
        show-sql: false
        generate-ddl: true
        hibernate:
            ddl-auto: none
    datasource:
        driverClassName: org.h2.Driver
        url: jdbc:h2:~/test
        username: sa
        password:

logging:
    level:
        org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG