server:
    port: 8080
grpc:
    port: 8081

spring:
    h2:
        console:
            enabled: true
            path: /h2-console
    jpa:
        show-sql: true
        generate-ddl: true
        hibernate:
            ddl-auto: none
    datasource:
        driverClassName: org.h2.Driver
        url: jdbc:h2:~/test
        username: sa
        password: