server:
    port: 8080

grpc:
    server:
        security:
            enabled: false
        port: 8081

spring:
    application:
        name: grpc-server
    sleuth:
        sampler:
            probability: 1.0
        enabled: true
        baggage:
            remote-fields:
                - X-USER-ID
                - x-user-id
            local-fields:
                - X-USER-ID
                - x-user-id
            correlation-fields:
                - X-USER-ID
                - x-user-id
        grpc:
              enabled: true
    h2:
        console:
            enabled: true
            path: /h2-console
    jpa:
        show-sql: false
        generate-ddl: true
        hibernate:
            ddl-auto: none
    datasource:
        driverClassName: org.h2.Driver
        url: jdbc:h2:~/test
        username: sa
        password:
    sql:
        init:
            mode: always
            platform: h2

logging:
    level:
        org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG